app/index/models.py
# -*- coding: UTF-8 -*-
import datetime

from ..app import db


class Product(db.Document):
    created_at = db.DateTimeField(default=datetime.datetime.now, required=True)
    key = db.StringField(max_length=255, required=True)
    name = db.StringField(max_length=255, required=True)
    price = db.DecimalField()

    def __str__(self):
        return '<Product %r>' % self.id

app/__init__.py
# -*- coding: UTF-8 -*-
from .app import app

# Blueprints registration
from . import index

app.register_blueprint(index.blueprint)

app/app.py
# -*- coding: UTF-8 -*-
import os

from flask import Flask
from flask_mongoengine import MongoEngine


BASE_DIR = os.path.dirname(os.path.abspath(__file__))
INSTANCE_DIR = os.path.abspath(os.path.join(BASE_DIR, '..', 'instance'))
STATIC_DIR = os.path.abspath(os.path.join(BASE_DIR, '..', 'static'))
TEMPLATE_DIR = os.path.abspath(os.path.join(BASE_DIR, '..', 'templates'))

app = Flask(
    __name__,
    instance_path=INSTANCE_DIR,
    instance_relative_config=True,
    static_folder=STATIC_DIR,
    template_folder=TEMPLATE_DIR
)
app.config.from_pyfile("config.py")

db = MongoEngine(app)

app/index/__init__.py
# -*- coding: UTF-8 -*-
from flask import Blueprint

blueprint = Blueprint('index', __name__)


from . import views
from . import filters

app/index/views.py
# -*- coding: UTF-8 -*-
from werkzeug import abort

from flask import render_template, request

from . import blueprint
from .models import Product


@blueprint.route('/')
def home():
    return render_template('index.html', products=Product.objects.filter())


@blueprint.route('/product/<key>/')
def product(key):
    product = Product.objects.get(key=key)
    if not product:
        abort(404)
    return render_template('product.html', product=product)

templates/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initialscale=1">
        <title>Flask Framework Cookbook</title>
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{{ url_for('index.home')}}">Flask Cookbook</a>
                </div>
            </div>
        </div>
        <div class="container">
            {% block container %}{% endblock %}
        </div>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block container %}
    <div class="top-pad">
    {% for product in products %}
        <div class="well">
            <h2>
                <a href="{{ url_for('index.product', key=product.key) }}">{{product['name'] }}</a>
                <small>$ {{ product.price }}</small>
            </h2>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/product.html
{% extends 'index.html' %}

{% block container %}
    <div class="top-pad">
        {#<h4>{{ product|full_name }}</h4>#}
        <h1>{{ product['name'] }}
            <small>{{ product['category'] }}</small>
        </h1>
        <h3>{{ product['price']|format_currency }}</h3>
    </div>
{% endblock %}